1986:
  - Licensed to Ill
1989:
  - "Paul's Boutique"
1992:
  - Check Your Head
1994:
  - Ill Communication
1998:
  - Hello Nasty
2004:
  - To the 5 Boroughs
2007:
  - The Mix-Up
2011:
  - Hot Sauce Committee Part Two
